spring.application.name=BillingSystem

server.port = 8081

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/billing_system}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:choinu}
spring.datasource.password=""

#health check
management.endpoints.web.exposure.include=health
management.endpoints.health.show-details=always